// Quran data layer — bundled Tanzil Uthmani text, read-only, offline, zero network (ADR 0016).
// Pure TS, no RN imports (CLAUDE.md). The reader UI consumes this module via its public API only.
//
// LICENCE (ADR 0016): the text is CC BY 3.0 and may ship in this commercial (ad-supported) app, but
// only VERBATIM and only with the copyright notice reproduced. Hence:
//   - nothing here rewrites, normalizes, or "cleans" the Arabic;
//   - QURAN_ATTRIBUTION is exported so the UI can display the notice + tanzil.net link. That display
//     is a licence condition — if the attribution surface is removed, the app loses its right to
//     ship the text.
//
// Data is regenerated by scripts/build-quran-data.mjs (see it for integrity guarantees).

import attributionJson from './data/attribution.json';
import surahsJson from './data/surahs.json';
import type { Ayah, QuranAttribution, SurahMeta, SurahText } from './types';

export type { Ayah, QuranAttribution, Revelation, SurahMeta, SurahText, VerseRef } from './types';
export { matchesSurah, normalizeTransliteration } from './search';

export const TOTAL_SURAHS = 114;
export const TOTAL_AYAT = 6236;

/** Surahs whose ayah 1 is NOT preceded by a separable basmala header — see BASMALA_WORD_COUNT. */
const AL_FATIHA = 1;
const AT_TAWBA = 9;

/**
 * The basmala is exactly four words: بسم / الله / الرحمن / الرحيم.
 *
 * We split ayah 1 on word count rather than by matching the basmala's text, because the text is NOT
 * byte-identical across surahs: in the Tanzil Uthmani edition, surahs 95 (At-Tin) and 97 (Al-Qadr)
 * spell it بِّسْمِ — with an extra shadda (U+0651) on the bāʾ — against بِسْمِ everywhere else. A
 * `startsWith` on Al-Fatiha's basmala therefore silently fails on exactly those two surahs and would
 * render their basmala as part of numbered ayah 1. Word-count splitting is invariant to that (and to
 * any other diacritic variation), and is verified for all 112 applicable surahs in the tests.
 */
const BASMALA_WORD_COUNT = 4;

type UthmaniData = {
  /** surahs[surahIndex][ayahIndex] — 0-based outer/inner, i.e. surahs[1][0] is 2:1. */
  surahs: string[][];
};

// Lazily required: the Uthmani JSON is ~1.3 MB, and expo-router eagerly evaluates every module
// reachable from app/, so a top-level import would parse the whole mushaf during app boot even for
// users who never open the Quran. Deferring to first read keeps that cost on the reader screen.
let cachedText: UthmaniData | null = null;
function uthmani(): UthmaniData {
  cachedText ??= require('./data/uthmani.json') as UthmaniData;
  return cachedText;
}

const SURAHS = surahsJson as readonly SurahMeta[];

/**
 * Source/licence metadata, held in its own ~1.5 KB file and imported eagerly.
 *
 * Deliberately NOT sourced from uthmani.json: the attribution must render on screens that show no
 * scripture (the surah list), and reading it through the lazy `uthmani()` accessor would parse the
 * entire 1.3 MB mushaf just to produce the string "https://tanzil.net" — giving back exactly the
 * boot/nav cost the lazy require exists to avoid. Plain values, not getters, so no caller can
 * accidentally reintroduce that coupling.
 */
export const QURAN_ATTRIBUTION: QuranAttribution = attributionJson;

export function isValidSurah(surah: number): boolean {
  return Number.isInteger(surah) && surah >= 1 && surah <= TOTAL_SURAHS;
}

/** True when (surah, ayah) is a real verse — surah 1-114 and ayah within that surah's count. */
export function isValidVerse(surah: number, ayah: number): boolean {
  return isValidSurah(surah) && Number.isInteger(ayah) && ayah >= 1 && ayah <= SURAHS[surah - 1].ayahCount;
}

/** All 114 surahs in mushaf order. */
export function listSurahs(): readonly SurahMeta[] {
  return SURAHS;
}

/** Surahs in revelation order (ADR 0016's "navigation/sort"). Does not mutate the cached list. */
export function listSurahsByRevelation(): readonly SurahMeta[] {
  return [...SURAHS].sort((a, b) => a.revelationOrder - b.revelationOrder);
}

export function getSurahMeta(surah: number): SurahMeta {
  if (!isValidSurah(surah)) throw new RangeError(`Surah must be 1-${TOTAL_SURAHS}, got ${surah}`);
  return SURAHS[surah - 1];
}

/**
 * A whole surah, ready to render: metadata, the basmala header (or null), and numbered ayat.
 *
 * The basmala is separated from ayah 1 for every surah except Al-Fatiha and At-Tawba. This is a
 * *presentation* split, not an edit: every character of the upstream text is still returned, just
 * apportioned between `bismillah` and `ayat[0].text` the way a printed mushaf lays it out. In
 * Al-Fatiha the basmala is itself numbered ayah 1, so splitting it would duplicate it; At-Tawba has
 * none.
 */
export function getSurah(surah: number): SurahText {
  const meta = getSurahMeta(surah);
  const raw = uthmani().surahs[surah - 1];

  const hasBasmalaHeader = surah !== AL_FATIHA && surah !== AT_TAWBA;
  let bismillah: string | null = null;
  let firstAyahText = raw[0];

  if (hasBasmalaHeader) {
    const words = raw[0].split(' ');
    bismillah = words.slice(0, BASMALA_WORD_COUNT).join(' ');
    firstAyahText = words.slice(BASMALA_WORD_COUNT).join(' ');
  }

  const ayat: Ayah[] = raw.map((text, i) => ({
    surah,
    ayah: i + 1,
    key: formatVerseKey(surah, i + 1),
    text: i === 0 ? firstAyahText : text,
  }));

  return { meta, bismillah, ayat };
}

export function getAyah(surah: number, ayah: number): Ayah {
  const meta = getSurahMeta(surah);
  if (!Number.isInteger(ayah) || ayah < 1 || ayah > meta.ayahCount) {
    throw new RangeError(`Ayah ${ayah} out of range for surah ${surah} (1-${meta.ayahCount})`);
  }
  // Ayah 1 needs the basmala split, so it goes through getSurah; every other ayah is a direct index
  // and skips rebuilding the whole surah.
  if (ayah === 1) return getSurah(surah).ayat[0];
  return {
    surah,
    ayah,
    key: formatVerseKey(surah, ayah),
    text: uthmani().surahs[surah - 1][ayah - 1],
  };
}

export function formatVerseKey(surah: number, ayah: number): string {
  return `${surah}:${ayah}`;
}

/** Parses "2:255". Returns null for malformed or out-of-range keys — callers get no partial answers. */
export function parseVerseKey(key: string): { surah: number; ayah: number } | null {
  const m = /^(\d+):(\d+)$/.exec(key.trim());
  if (!m) return null;
  const surah = Number(m[1]);
  const ayah = Number(m[2]);
  if (!isValidSurah(surah)) return null;
  if (!Number.isInteger(ayah) || ayah < 1 || ayah > SURAHS[surah - 1].ayahCount) return null;
  return { surah, ayah };
}
